# Generated by Django 3.0.6 on 2020-05-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_image_imade_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imade_description',
            new_name='image_description',
        ),
    ]
